{% set name = "sagemaker-tensorflow-container" %}
{% set version = "3.2.3.post0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/aws/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: b8dc8b2df9b4ee58433c97739f7fb63e8e55db211c03fb6a7f378d1a296608d1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - sagemaker_containers
    - numpy >=1.14.0
    - scipy
    - scikit-learn
    - pandas
    - Pillow
    - h5py

test:
  imports:
    - sagemaker_tensorflow_container

about:
  home: https://github.com/aws/sagemaker-tensorflow-container
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: SageMaker TensorFlow Containers is an open source library for making the TensorFlow framework run on Amazon SageMaker.
  dev_url: https://github.com/aws/sagemaker-tensorflow-container

extra:
  recipe-maintainers:
    - oblute
    - rluria14
    - mwilson8
